apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJaV05vYnlBdGJpQmhiR1ZyYzJWNU5qRTFNQzB5T21kb2NGOVlhV3B1UWtwNVlrZFFTek5QYzI1VmJXczRRM0o2ZEVjMVNqTlBlVFF3Y2xSaFFub2dmQ0JpWVhObE5qUUsiCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
