apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJZV3hsYTNObGVUWXhOVEF0TWpwbmFIQmZXR2xxYmtKS2VXSkhVRXN6VDNOdVZXMXJPRU55ZW5SSE5Vb3pUM2swTUhKVVlVSjYiCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
