{{- if .Values.proxyService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: proxy-service
    app.kubernetes.io/name: {{ include "cinemaabyss.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.proxyService.replicas }}
  selector:
    matchLabels:
      app: proxy-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: proxy-service
    spec:
      containers:
      - name: proxy-service
        image: {{ .Values.proxyService.image.repository }}:{{ .Values.proxyService.image.tag }}
        imagePullPolicy: {{ .Values.proxyService.image.pullPolicy }}
        ports:
        - containerPort: 8000
        env:
        - name: MONOLITH_URL
          valueFrom:
            configMapKeyRef:
              name: cinemaabyss-config
              key: MONOLITH_URL
        - name: EVENTS_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: cinemaabyss-config
              key: EVENTS_SERVICE_URL
        - name: MOVIES_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: cinemaabyss-config
              key: MOVIES_SERVICE_URL
        - name: GRADUAL_MIGRATION
          valueFrom:
            configMapKeyRef:
              name: cinemaabyss-config
              key: GRADUAL_MIGRATION
        - name: MOVIES_MIGRATION_PERCENT
          valueFrom:
            configMapKeyRef:
              name: cinemaabyss-config
              key: MOVIES_MIGRATION_PERCENT
        resources:
          { { - toYaml .Values.eventsService.resources | nindent 10 } }
        readinessProbe:
          httpGet:
            path: /api/proxy/health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/proxy/health
            port: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: proxy-service
    app.kubernetes.io/name: {{ include "cinemaabyss.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    ... и тут
{{- end }}